language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

before_install:
  - npm set progress=false

install:
  - npm install

script:
  - npm run pretty
  - npm test
  - npm run build:css

after_success:
  - npm run coverage
